name: LIVE - Publish Libraries & Deploy App
'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo âœ…
        uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: NRWL setup âœ…
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies ğŸ”§
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Lint â™»ï¸
        run: npx nx affected -t lint

      - name: Build ğŸ“¦
        run: npx nx affected -t build

      - name: Test ğŸ§ª
        run: npx nx affected -t test --ci --code-coverage

      - name: Release ğŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx run-many --target=deploy --parallel=false

      - name: Deploy to Firebase ğŸ”¥
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NX_ANGULAR_RELEASE }}'
          channelId: live
          projectId: nx-angular-release
